version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8060:8060"
    environment:
      - NODE_ENV=production

  user-service:
    build: ./user-service
    ports:
      - "8062:8062"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "8075:8075"
    environment:
      - NODE_ENV=production

  api-gateway:
    build: ./api-gateway
    ports:
      - "8076:8076"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx
    ports:
      - "8077:8077"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/46.17.40.33/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/46.17.40.33/privkey.pem:/etc/nginx/ssl/privkey.pem
