version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8060:8060"
    environment:
      - NODE_ENV=production

  account-service:
    build: ./account-service
    ports:
      - "8061:8061"
    environment:
      - NODE_ENV=production

  user-service:
    build: ./user-service
    ports:
      - "8062:8062"
    environment:
      - NODE_ENV=production

  elderly-service:
    build: ./elderly-service
    ports:
      - "8063:8063"
    environment:
      - NODE_ENV=production

 

  employee-service:
    build: ./employee-service
    ports:
      - "8065:8065"
    environment:
      - NODE_ENV=production

  bed-service:
    build: ./bed-service
    ports:
      - "8066:8066"
    environment:
      - NODE_ENV=production




  frontend:
    build: ./frontend
    ports:
      - "8075:8075"
    environment:
      - NODE_ENV=production

  api-gateway:
    build: ./api-gateway
    ports:
      - "8076:8076"
    environment:
      - NODE_ENV=production
