name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy code to remote server
        run: |
          scp -r . Vstu2025@46.17.40.33:/xiongshuqiu/myapp

      - name: Deploy to remote server
        run: |
          ssh Vstu2025@46.17.40.33 "cd /xiongshuqiu/myapp && docker-compose up -d --build"
