name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.A }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 46.17.40.33 >> ~/.ssh/known_hosts

      - name: Copy code to remote server
        run: |
          scp -r . root@46.17.40.33:/xiongshuqiu/myapp

      - name: Deploy to remote server
        run: |
          ssh root@46.17.40.33 "cd /xiongshuqiu/myapp && docker-compose up -d --build"


          